apiVersion: v1
kind: Service
metadata:
  name: vertex-api-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
      app.kubernetes.io/name: api-vertx
